functional:
  - Пользователь должен иметь возможность авторизоваться.
  - Пользователь должен иметь возможность создать игру.
  - Пользователь должен иметь возможность завершить игру досрочно.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Сайт должен иметь русскоязычную версию.
  - Пользователь должен иметь возможность через Google аккаунт.
